# Generated by Django 4.2.11 on 2024-04-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='location name')),
                ('address_line', models.CharField(max_length=300, verbose_name='address line')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('country', models.CharField(max_length=3, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('desc', models.CharField(max_length=300, verbose_name='description')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='amount')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('desc', models.CharField(max_length=300, verbose_name='description')),
                ('place', models.CharField(max_length=150, verbose_name='place')),
                ('when', models.DateTimeField(verbose_name='when it will happen')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='events.location'),
            preserve_default=False,
        ),
    ]
