# Generated by Django 4.2.11 on 2024-03-29 18:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contact', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='social media link')),
                ('platform', models.CharField(choices=[('X', 'x'), ('INSTAGRAM', 'instagram'), ('FACEBOOK', 'facebook')], verbose_name='social media platform')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='events.event')),
            ],
            options={
                'unique_together': {('link', 'event')},
            },
        ),
    ]
