# Generated by Django 4.2.11 on 2024-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_event_end_event_start_alter_event_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.URLField(blank=True, null=True, verbose_name='picture'),
        ),
    ]
