# Generated by Django 4.2.11 on 2024-05-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount',
        ),
    ]
