# Generated by Django 4.2.11 on 2024-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_eventreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[(2, 'important'), (1, 'reminder'), (0, 'casual')], verbose_name='notification type'),
        ),
    ]
